# Generated by Django 4.2.3 on 2023-08-03 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.department')),
            ],
        ),
    ]
